#ifndef _KTSDKERR__H
#define _KTSDKERR__H

#define KTSDK_ERR_OK						0
#define KTSDK_ERR_INDATA					1001
#define KTSDK_ERR_MEMORY					1002
#define KTSDK_ERR_NOTSUPPORTED				1003
#define KTSDK_ERR_OBJNOTFOUND				1004

#define KTSDK_ERR_INITIALIZE				1011
#define KTSDK_ERR_FINALIZE					1012

#define KTSDK_ERR_BASE64ENCODE				1021
#define KTSDK_ERR_JAVADATAENCODE			1022
#define KTSDK_ERR_CERTENCODE				1023
#define KTSDK_ERR_GETCERTINFO				1024

#define KTSDK_ERR_HASHDATA					1031
#define KTSDK_ERR_HASHDATANOTMATCH			1032

#define KTSDK_ERR_RSASIGN					1041
#define KTSDK_ERR_RSAVERIFYSIGN				1042
#define KTSDK_ERR_RSAENCRYPT				1043
#define KTSDK_ERR_RSADECRYPT				1044

#define KTSDK_ERR_SM2ENCODE					1051
#define KTSDK_ERR_SM3HASH					1052
#define KTSDK_ERR_SM2YCL					1053
#define KTSDK_ERR_SM2SIGN					1054
#define KTSDK_ERR_SM2VERIFYSIGN				1055
#define KTSDK_ERR_SM2ENCRYPT				1056
#define KTSDK_ERR_SM2DECRYPT				1057

#define KTSDK_ERR_DEVICE_LOADLIBRARY		1101
#define KTSDK_ERR_DEVICE_GETFUNCTIONLIST	1102
#define KTSDK_ERR_DEVICE_INITIALIZE			1103
#define KTSDK_ERR_DEVICE_FINALIZE			1104
#define KTSDK_ERR_DEVICE_GETDEVICECOUNT		1105
#define KTSDK_ERR_DEVICE_DEVICENOTFOUND		1106
#define KTSDK_ERR_DEVICE_GETINFO			1107
#define KTSDK_ERR_DEVICE_INITDEVICE			1108

#define KTSDK_ERR_DEVICE_OPENSESSION		1111
#define KTSDK_ERR_DEVICE_SESSIONNOTOPENED	1112
#define KTSDK_ERR_DEVICE_CLOSESESSION		1113
#define KTSDK_ERR_DEVICE_LOGIN				1114
#define KTSDK_ERR_DEVICE_LOGOUT				1115
#define KTSDK_ERR_DEVICE_SETPIN				1116
#define KTSDK_ERR_DEVICE_GETREMAINRETRYCOUT	1117
#define KTSDK_ERR_DEVICE_GETSESSIONINFO		1118

#define KTSDK_ERR_DEVICE_LOOKUPCERT			1121
#define KTSDK_ERR_DEVICE_CERTNOTFOUND		1122
#define KTSDK_ERR_DEVICE_READCERT			1123
#define KTSDK_ERR_DEVICE_WRITECERT			1124
#define KTSDK_ERR_DEVICE_DELETECERT			1125

#define KTSDK_ERR_DEVICE_LOOKUPPUBKEY		1131
#define KTSDK_ERR_DEVICE_PUBKEYNOTFOUND		1132
#define KTSDK_ERR_DEVICE_GETPUBKEY			1133
#define KTSDK_ERR_DEVICE_GENKEY				1134
#define KTSDK_ERR_DEVICE_IMPORTPUBKEY		1135
#define KTSDK_ERR_DEVICE_DELETEPUBKEY		1136

#define KTSDK_ERR_DEVICE_LOOKUPPRVKEY		1141
#define KTSDK_ERR_DEVICE_PRVKEYNOTFOUND		1142
#define KTSDK_ERR_DEVICE_IMPORTPRVKEY		1143
#define KTSDK_ERR_DEVICE_DELETEPRVKEY		1144

#define KTSDK_ERR_DEVICE_RSASIGN			1151
#define KTSDK_ERR_DEVICE_RSAVERIFYSIGN		1152
#define KTSDK_ERR_DEVICE_RSAENCRYPT			1153
#define KTSDK_ERR_DEVICE_RSADECRYPT			1154

#define KTSDK_ERR_DEVICE_SM3HASH			1161
#define KTSDK_ERR_DEVICE_SM2YCL				1162
#define KTSDK_ERR_DEVICE_SM2SIGN			1163
#define KTSDK_ERR_DEVICE_SM2VERIFYSIGN		1164
#define KTSDK_ERR_DEVICE_SM2ENCRYPT			1165
#define KTSDK_ERR_DEVICE_SM2DECRYPT			1166

#define KTSDK_ERR_DEVICE_IMPORTSYMMKEY		1171
#define KTSDK_ERR_DEVICE_ENCRYPTINIT		1172
#define KTSDK_ERR_DEVICE_ENCRYPTUPDATE		1173
#define KTSDK_ERR_DEVICE_ENCRYPTFINAL		1174
#define KTSDK_ERR_DEVICE_DECRYPTINIT		1175
#define KTSDK_ERR_DEVICE_DECRYPTUPDATE		1176
#define KTSDK_ERR_DEVICE_DECRYPTFINAL		1177
#define KTSDK_ERR_DEVICE_DELETESYMMKEY		1178

#define KTSDK_ERR_DEVICE_ENUMFILE			1181
#define KTSDK_ERR_DEVICE_CREATEFILE			1182
#define KTSDK_ERR_DEVICE_DELETEFILE			1183
#define KTSDK_ERR_DEVICE_GETFILEINFO		1184
#define KTSDK_ERR_DEVICE_READFILE			1185
#define KTSDK_ERR_DEVICE_WRITEFILE			1186
#define KTSDK_ERR_DEVICE_LOOKUPFILE			1187
#define KTSDK_ERR_DEVICE_FILENOTFOUND		1188
#define KTSDK_ERR_DEVICE_FILEEXISTS			1189

// skf´íÎóÂë
#define KTSDK_ERR_SKF_OK					0
#define KTSDK_ERR_SKF_PARAMETER				2101
#define KTSDK_ERR_SKF_NOTSUPPORTED			2102
#define KTSDK_ERR_SKF_MEMORY				2103
#define KTSDK_ERR_SKF_BASE64				2104
#define KTSDK_ERR_SKF_CERT					2105
#define KTSDK_ERR_SKF_USERCANCEL			2106
#define KTSDK_ERR_SKF_LOADDLL				2107
#define KTSDK_ERR_SKF_INIT					2108

#define KTSDK_ERR_SKF_DEV_NOTFOUND			2111
#define KTSDK_ERR_SKF_DEV_OPEN				2112
#define KTSDK_ERR_SKF_DEV_NOTOPEN			2113
#define KTSDK_ERR_SKF_DEV_GETINFO			2114
#define KTSDK_ERR_SKF_DEV_GENRANDOM			2115
#define KTSDK_ERR_SKF_DEV_AUTH				2116

#define KTSDK_ERR_SKF_APPLICATION_NOTFOUND	2121
#define KTSDK_ERR_SKF_APPLICATION_OPEN		2122
#define KTSDK_ERR_SKF_APPLICATION_CREATE	2123
#define KTSDK_ERR_SKF_APPLICATION_DELETE	2124

#define KTSDK_ERR_SKF_CONTAINER_NOTFOUND	2131
#define KTSDK_ERR_SKF_CONTAINER_OPEN		2132
#define KTSDK_ERR_SKF_CONTAINER_CREATE		2133
#define KTSDK_ERR_SKF_CONTAINER_DELETE		2134
#define KTSDK_ERR_SKF_CONTAINER_TOOMANY		2135

#define KTSDK_ERR_SKF_VERIFYPIN				2141
#define KTSDK_ERR_SKF_CHANGEPIN				2142
#define KTSDK_ERR_SKF_PINLOCKED				2143
#define KTSDK_ERR_SKF_UNLOCKPIN				2144

#define KTSDK_ERR_SKF_READCERT				2151
#define KTSDK_ERR_SKF_WRITECERT				2152
#define KTSDK_ERR_SKF_GENKEYPAIR			2153
#define KTSDK_ERR_SKF_GETPUBKEY				2154
#define KTSDK_ERR_SKF_CREATEREQ				2155
#define KTSDK_ERR_SKF_CREATEREQ_SETDN		2156
#define KTSDK_ERR_SKF_PARSEKEYPAIR			2157
#define KTSDK_ERR_SKF_IMPORTKEYPAIR			2158
#define KTSDK_ERR_SKF_GENCONTAINERNAME		2159

#define KTSDK_ERR_SKF_HASHDATA				2161
#define KTSDK_ERR_SKF_RSASIGN				2162
#define KTSDK_ERR_SKF_RSAVERIFYSIGN			2163
#define KTSDK_ERR_SKF_RSAENCRYPT			2164
#define KTSDK_ERR_SKF_RSADECRYPT			2165
#define KTSDK_ERR_SKF_SM2SIGN				2166
#define KTSDK_ERR_SKF_SM2VERIFYSIGN			2167
#define KTSDK_ERR_SKF_SM2ENCRYPT			2168
#define KTSDK_ERR_SKF_SM2DECRYPT			2169

#define KTSDK_ERR_SKF_SETSYMMKEY			2171
#define KTSDK_ERR_SKF_ENCRYPTINIT			2172
#define KTSDK_ERR_SKF_ENCRYPTUPDATE			2173
#define KTSDK_ERR_SKF_ENCRYPTFINAL			2174
#define KTSDK_ERR_SKF_DECRYPTINIT			2175
#define KTSDK_ERR_SKF_DECRYPTUPDATE			2176
#define KTSDK_ERR_SKF_DECRYPTFINAL			2177

#define KTSDK_ERR_SKF_ENUMFILE				2181
#define KTSDK_ERR_SKF_CREATEFILE			2182
#define KTSDK_ERR_SKF_DELETEFILE			2183
#define KTSDK_ERR_SKF_GETFILEINFO			2184
#define KTSDK_ERR_SKF_READFILE				2185
#define KTSDK_ERR_SKF_WRITEFILE				2186

// could cert´íÎóÂë
#define KTSDK_ERR_CC_OK						0
#define KTSDK_ERR_CC_PARAMETER				3101
#define KTSDK_ERR_CC_NOTSUPPORTED			3102
#define KTSDK_ERR_CC_MEMORY					3103
#define KTSDK_ERR_CC_BASE64					3104
#define KTSDK_ERR_CC_CERT					3105
#define KTSDK_ERR_CC_USERCANCEL				3106
#define KTSDK_ERR_CC_LOADDLL				3107
#define KTSDK_ERR_CC_INIT					3108

#define KTSDK_ERR_CC_NOTFOUND				3111
#define KTSDK_ERR_CC_OPEN					3112
#define KTSDK_ERR_CC_NOTOPEN				3113
#define KTSDK_ERR_CC_GETINFO				3114
#define KTSDK_ERR_CC_GENRANDOM				3115
#define KTSDK_ERR_CC_AUTH					3116

#define KTSDK_ERR_CC_VERIFYPIN				3121
#define KTSDK_ERR_CC_CHANGEPIN				3122
#define KTSDK_ERR_CC_PINLOCKED				3123
#define KTSDK_ERR_CC_UNLOCKPIN				3124

#define KTSDK_ERR_CC_READCERT				3131
#define KTSDK_ERR_CC_WRITECERT				3132
#define KTSDK_ERR_CC_GENKEYPAIR				3133
#define KTSDK_ERR_CC_GETPUBKEY				3134
#define KTSDK_ERR_CC_CREATEREQ				3135
#define KTSDK_ERR_CC_CREATEREQ_SETDN		3136
#define KTSDK_ERR_CC_PARSEKEYPAIR			3137
#define KTSDK_ERR_CC_IMPORTKEYPAIR			3138

#define KTSDK_ERR_CC_HASHDATA				3141
#define KTSDK_ERR_CC_RSASIGN				3142
#define KTSDK_ERR_CC_RSAVERIFYSIGN			3143
#define KTSDK_ERR_CC_RSAENCRYPT				3144
#define KTSDK_ERR_CC_RSADECRYPT				3145
#define KTSDK_ERR_CC_SM2SIGN				3146
#define KTSDK_ERR_CC_SM2VERIFYSIGN			3147
#define KTSDK_ERR_CC_SM2ENCRYPT				3148
#define KTSDK_ERR_CC_SM2DECRYPT				3149

// pfx´íÎóÂë
#define KTSDK_ERR_PFX_OK					0
#define KTSDK_ERR_PFX_PARAMETER				4101
#define KTSDK_ERR_PFX_NOTSUPPORTED			4102
#define KTSDK_ERR_PFX_MEMORY				4103
#define KTSDK_ERR_PFX_BASE64				4104
#define KTSDK_ERR_PFX_CERT					4105
#define KTSDK_ERR_PFX_USERCANCEL			4106
#define KTSDK_ERR_PFX_LOADDLL				4107
#define KTSDK_ERR_PFX_KEY					4108

#define KTSDK_ERR_PFX_NOTFOUND				4111
#define KTSDK_ERR_PFX_OPEN					4112
#define KTSDK_ERR_PFX_NOTOPEN				4113
#define KTSDK_ERR_PFX_GETINFO				4114
#define KTSDK_ERR_PFX_GENRANDOM				4115
#define KTSDK_ERR_PFX_AUTH					4116

#define KTSDK_ERR_PFX_VERIFYPIN				4121
#define KTSDK_ERR_PFX_CHANGEPIN				4122
#define KTSDK_ERR_PFX_PINLOCKED				4123
#define KTSDK_ERR_PFX_UNLOCKPIN				4124

#define KTSDK_ERR_PFX_CERT_NOTFOUND			4131
#define KTSDK_ERR_PFX_READCERT				4132
#define KTSDK_ERR_PFX_WRITECERT				4133
#define KTSDK_ERR_PFX_GENKEYPAIR			4134
#define KTSDK_ERR_PFX_GETPUBKEY				4135
#define KTSDK_ERR_PFX_CREATEREQ				4136
#define KTSDK_ERR_PFX_CREATEREQ_SETDN		4137
#define KTSDK_ERR_PFX_PARSEKEYPAIR			4138
#define KTSDK_ERR_PFX_IMPORTKEYPAIR			4139

#define KTSDK_ERR_PFX_KEY_NOTFOUND			4141
#define KTSDK_ERR_PFX_READKEY				4142
#define KTSDK_ERR_PFX_WRITEKEY				4143
#define KTSDK_ERR_PFX_ISSUECERT				4144

#define KTSDK_ERR_PFX_HASHDATA				4151
#define KTSDK_ERR_PFX_RSASIGN				4152
#define KTSDK_ERR_PFX_RSAVERIFYSIGN			4153
#define KTSDK_ERR_PFX_RSAENCRYPT			4154
#define KTSDK_ERR_PFX_RSADECRYPT			4155
#define KTSDK_ERR_PFX_SM2SIGN				4156
#define KTSDK_ERR_PFX_SM2VERIFYSIGN			4157
#define KTSDK_ERR_PFX_SM2ENCRYPT			4158
#define KTSDK_ERR_PFX_SM2DECRYPT			4159

#endif
