#ifndef __KT_ERR_NUM_H_
#define __KT_ERR_NUM_H_

/**
  *@Name: KTErrNum.h
  *@Copyright: KTXA SoftWare
  *@Author: Hongwei Yu
  *@Date:  2003/04/03 15:49
  *@Description: all error number 
*/

#ifdef KT_WIN32
	#pragma pack(push,1)
#endif

#include "./KTType.h"

enum enumKTError
{
    KT_OK,
	KT_ERR_CANCEL,
	KT_ERR_UNKNOWN,
	KT_ERR_INTERNAL,
	KT_ERR_CRNT_NOSUPPORT,//4
	
	KT_ERR_MSG_FORMAT,
	KT_ERR_INTERRUPTED,
	KT_ERR_CONNECT_FAILED,
 	KT_ERR_NOENOUGH_MEM,
 	KT_ERR_ILLEGAL_ACCESS,
	KT_ERR_BOUNDS,//10

    ////token
    KT_ERR_NOSTART, 
	KT_ERR_NOACTIVE,
	KT_ERR_TOKEN,
	KT_ERR_OPERATION,
 	KT_ERR_INVALID_STATE,
	KT_ERR_TOKEN_EXPIRED,
	KT_ERR_SHOULD_TRY_LATER,//17

 	///argument
    KT_ERR_PARSING,
    KT_ERR_ZERO_LENGTH,
    KT_ERR_NULL_POINTER,
	KT_ERR_BUFFER_SMALL,
    KT_ERR_INVALID_ARGUMENT,//22

 	////IO
	KT_ERR_INPUT,
    KT_ERR_OUTPUT,
    KT_ERR_IO,					//25

 	////obj
	KT_ERR_OBJ_NOT_FOUND,
 	KT_ERR_OBJ_EXISTED,		//27

	KT_ERR_AUTHORIZED,
	KT_ERR_RSA_DECRYPT,
	KT_ERR_INVALID_DATE,
	KT_ERR_RSA_INPUT_LEN,
	KT_ERR_VERIFY_FAILED,
	KT_ERR_CERTCHAIN_DEFORMITY,//33

	KT_ERR_ICCARD,	
	KT_ERR_ICCARD_GEN_KEY,
	KT_ERR_ICCARD_ENCRYPT,
	KT_ERR_ICCARD_DECRYPT,
	KT_ERR_ICCARD_PUT_RSA_KEY,//38

	KT_ERR_DEVICE,
	KT_ERR_READER,
	KT_ERR_INVALID_KEY,
	KT_ERR_CHECKSUM,
	KT_ERR_INVAILD_PIN_LEN,  //43
	
    //asn and pkcs
    KT_ERR_ASN_TYPE,
    KT_ERR_ASN_DATA,
    KT_ERR_ASN_LEN_CONFLICT,
    KT_ERR_ASN_OBJID_NOT_FOUND,
    KT_ERR_ASN_OBJID_NOT_SUPPORT,  //48
    
    KT_ERR_CERT_TIME_BEFORE_ISSURE,
    KT_ERR_CERT_TIME_AFTER_ISSURE,
    KT_ERR_CERT_TIME_BEFORE_VALIDITY,
    KT_ERR_CERT_TIME_AFTER_VALIDITY,
    KT_ERR_CERT_ISSUER_NAME_IDENTICAL,
    KT_ERR_CERT_NO_KEY_ID,
    KT_ERR_CERT_ISSUER_KEYID_IDENTICAL, //55

    KT_ERR_PKCS_NO_MACDATA,
    KT_ERR_PKCS_DIGEST_NOT_MATCH,
    KT_ERR_PKCS_GEN_DIGEST,        //58
    
    KT_ERR_CRYPT_PACK_LENGTH,
    
    KT_ERR_ASN_LARGEST_OBJID,    
    KT_ERR_ASN_CHOICE_CONFLICT,	// used in createContent() in KTChoice derived class

    KT_ERR_UNSPECIFY,	
	KT_ERR_NO_THIS_FILE,			//63

	KT_ERR_SIGN_VERSION,
	KT_ERR_ENCRYPT_VERSION,
	KT_ERR_ENVELOP_VERSION,
	KT_ERR_CIPHER_VERSION,			//67

	KT_ERR_OPEN_FILE,
	KT_ERR_SIGN_FILE_HEAD,
	KT_ERR_ENCRYPT_FILE_HEAD,
	KT_ERR_ENVELOP_FILE_HEAD,
	KT_ERR_ENCRYPT_FILE_SIZE_THAN_4G,	//72

	KT_ERR_INVALID_COMPONENT,		// 73, one or more component is invalid
	KT_ERR_INVALID_SESSION,			// 74, invalid KT_SESSION_HANDLE

	KT_ERR_SM2_KEY,
	KT_ERR_SM2_YCL,
	KT_ERR_SM2_SIGN,
	KT_ERR_SM2_VERIFYSIGN,
	KT_ERR_SM2_ENCRYPT,
	KT_ERR_SM2_DECRYPT,
	KT_ERR_SM2_KEYEXCHANG,
	KT_ERR_SM3_OPERATION,			// 82

	KT_ERR_SYMM_IMPORTSESSIONKEY,
	KT_ERR_SYMM_SETSYMMKEY,
	KT_ERR_SYMM_ENCRYPT_INIT,
	KT_ERR_SYMM_ENCRYPT,
	KT_ERR_SYMM_ENCRYPT_UPDATE,
	KT_ERR_SYMM_ENCRYPT_FINAL,
	KT_ERR_SYMM_DECRYPT_INIT,
	KT_ERR_SYMM_DECRYPT,
	KT_ERR_SYMM_DECRYPT_UPDATE,
	KT_ERR_SYMM_DECRYPT_FINAL,
	KT_ERR_PKCS5_PADDING,			// 93

	KT_ERR_SERVICE_INIT				// 94
};

#ifdef KT_WIN32
	#pragma pack(pop)
#endif

/*
/// Rivison history
/// ----------------------------------------------------------------------------
/// 	Version	       Date        Author      Note
/// ----------------------------------------------------------------------------
///   1.0.0.0  2003/04/03 16:14  Hongwei Yu   created 
///   1.0.0.1  2003/04/04 16:14  Hongwei Yu   refactory 
**/
#endif //
