#ifndef __PKI_INTERFACE_H_INCLUDE__
#define __PKI_INTERFACE_H_INCLUDE__

/**
  * @Name: PKIInterface.h
  * @Copyright: KTXA SoftWare
  * @Author: Hongwei Yu
  * @Date:  2003/04/25 14:19
  * @Description: 定义PKISDK中的ClassID和接口ID
*/

#include	"KTInterface.h"

const KTUINT32		KT_LIB_MODEID_KPSDK_BASE				=	KT_LIB_MODEID_BASE;
const KTUINT32		KT_INTERFACEID_KPSDK_BASE			    =	KT_INTERFACEID_BASE;
///////////////////////////////////////////////////////////////////////
//define class id.
const KTCID		KTCID_ICC_TOKEN					=	KT_LIB_MODEID_KPSDK_BASE-1;
const KTCID		KTCID_FILE_TOKEN				=	KT_LIB_MODEID_KPSDK_BASE-2;
const KTCID		KTCID_EMC_TOKEN					=	KT_LIB_MODEID_KPSDK_BASE-3;
const KTCID		KTCID_IKEY_TOKEN				=	KT_LIB_MODEID_KPSDK_BASE-4;
const KTCID		KTCID_FLOPPY_TOKEN				=	KT_LIB_MODEID_KPSDK_BASE-5;
const KTCID		KTCID_SHECA_FILE_TOKEN			=	KT_LIB_MODEID_KPSDK_BASE-6;
const KTCID		KTCID_GPK_TOKEN					=	KT_LIB_MODEID_KPSDK_BASE-7;	
const KTCID		KTCID_SJY05EM_TOKEN				=	KT_LIB_MODEID_KPSDK_BASE-8;	
const KTCID		KTCID_SMARTKEY_TOKEN			=	KT_LIB_MODEID_KPSDK_BASE-9;	
const KTCID		KTCID_PUBLIC_TOKEN				=	KT_LIB_MODEID_KPSDK_BASE-10;
const KTCID		KTCID_SJY36EM_TOKEN				=	KT_LIB_MODEID_KPSDK_BASE-11;	

const KTCID		KTCID_FILE_SLOT					=	KT_LIB_MODEID_KPSDK_BASE-51;
const KTCID		KTCID_ICC_SLOT					=	KT_LIB_MODEID_KPSDK_BASE-52;
const KTCID		KTCID_IKEY_SLOT					=	KT_LIB_MODEID_KPSDK_BASE-53;
const KTCID		KTCID_FLOPPY_SLOT				=	KT_LIB_MODEID_KPSDK_BASE-54;
const KTCID		KTCID_SHECA_FILE_SLOT			=	KT_LIB_MODEID_KPSDK_BASE-55;
const KTCID		KTCID_GPK_SLOT					=	KT_LIB_MODEID_KPSDK_BASE-56;
const KTCID		KTCID_EMC_SLOT					=	KT_LIB_MODEID_KPSDK_BASE-57;
const KTCID		KTCID_PFX_SLOT					=	KT_LIB_MODEID_KPSDK_BASE-58;
const KTCID		KTCID_SMARTKEY_SLOT				=	KT_LIB_MODEID_KPSDK_BASE-59;
const KTCID		KTCID_PLUG_SLOT				    =	KT_LIB_MODEID_KPSDK_BASE-60;
const KTCID		KTCID_MWKEY_SLOT				=	KT_LIB_MODEID_KPSDK_BASE-61;


const KTCID		KTCID_FILE_SLOT_MANGR			=	KT_LIB_MODEID_KPSDK_BASE-101;
const KTCID		KTCID_ICC_SLOT_MANGR			=	KT_LIB_MODEID_KPSDK_BASE-102;
const KTCID		KTCID_IKEY_SLOT_MANGR			=	KT_LIB_MODEID_KPSDK_BASE-103;
const KTCID		KTCID_FLOPPY_SLOT_MANGR			=	KT_LIB_MODEID_KPSDK_BASE-104;
const KTCID		KTCID_SHECA_FILE_SLOT_MANGR		=	KT_LIB_MODEID_KPSDK_BASE-105;
const KTCID		KTCID_GPK_SLOT_MANGR			=	KT_LIB_MODEID_KPSDK_BASE-106;
const KTCID		KTCID_EMC_SLOT_MANGR			=	KT_LIB_MODEID_KPSDK_BASE-107;
const KTCID		KTCID_PFX_SLOT_MANGR			=	KT_LIB_MODEID_KPSDK_BASE-108;
const KTCID		KTCID_SMARTKEY_SLOT_MANGR		=	KT_LIB_MODEID_KPSDK_BASE-109;
const KTCID		KTCID_PLUG_SLOT_MANGR			=	KT_LIB_MODEID_KPSDK_BASE-110;
const KTCID		KTCID_MWKEY_SLOT_MANGR		    =	KT_LIB_MODEID_KPSDK_BASE-111;

///////////////////////////////////////////////////////////////////////
//define interface id.

const KTIID		KTIID_TOKEN						=	KT_INTERFACEID_KPSDK_BASE-2;
const KTIID		KTIID_RSACIPHER_H				=	KT_INTERFACEID_KPSDK_BASE-3;  //for hardware.
const KTIID		KTIID_TOKEN_PERSONAL			=	KT_INTERFACEID_KPSDK_BASE-5;
const KTIID		KTIID_SLOT						=	KT_INTERFACEID_KPSDK_BASE-7;
const KTIID		KTIID_TOKEN2					=   KT_INTERFACEID_KPSDK_BASE-8;	//2000.11.11
const KTIID		KTIID_SLOT_MANGR				=	KT_INTERFACEID_KPSDK_BASE-9;

const KTIID		KTIID_TOKEN_OBJECT_MANGR		=	KT_INTERFACEID_KPSDK_BASE-300;
const KTIID		KTIID_TOKEN_KEY_MANGR			=	KT_INTERFACEID_KPSDK_BASE-301;
const KTIID		KTIID_TOKEN_CIPHER				=	KT_INTERFACEID_KPSDK_BASE-302;
const KTIID		KTIID_TOKEN_SIGN				=	KT_INTERFACEID_KPSDK_BASE-304;
const KTIID		KTIID_TOKEN_ENVELOP				=	KT_INTERFACEID_KPSDK_BASE-305;
const KTIID		KTIID_TOKEN_POLICY				=	KT_INTERFACEID_KPSDK_BASE-306;

const KTIID		KTIID_TOKEN_SERVER				=	KT_INTERFACEID_KPSDK_BASE-350;

/// Rivison history
/// ----------------------------------------------------------------------------
/// 	Version	       Date        Author      Note
/// ----------------------------------------------------------------------------
///   1.0.0.0  2003/04/25 14:19  Hongwei Yu   created 

#endif //__PKI_INTERFACE_H_INCLUDE__
